### ISSUE TITLE
Stopping working for me

### ISSUE THREAD

**Issue by livefeed** [apetrycki/daikinskyport#28]
Hi, First thank you for working on this. Not sure if this is just me but this was working great but now it's not working, HA is up to date and the logs just say gave up trying to connect. Any ideas?

**Comment by apetrycki** [comment]
If you provide more info, we can take a look at it.  Post your logs as well.  You can also manually poll the API with the info in API_info.md and make sure your thermostat is working correctly.  Usually when I have issues it's because the thermostat isn't connected to my wifi when HA starts like after a power outage.

**Comment by livefeed** [comment]
Waiting on integrations to complete setup: daikinskyport
9:16:53 PM – (WARNING) bootstrap.py - message first occurred at 9:14:51 PM and shows up 3 times

Thermostat is connected to the internet as I can connect using the app.

**Comment by livefeed** [comment]
Update: all working turned out my sky port account had an issue.
Thank you for your great work.

**Comment by apetrycki** [comment]
Great, glad it's working for you.
