### ISSUE TITLE
Temperature change requires two tries

### ISSUE THREAD

**Issue by dualtronic** [apetrycki/daikinskyport#81]
Using the standard UI thermostat, the temperature change button does not change the setpoint unless you exit the thermostat, open the thermostat again, and then click the temperature change  button for the second time. Only then will the actual temperature setpoint be updated.

**Comment by apetrycki** [comment]
I can't replicate this problem.  Sometimes it takes a while for the thermostat/API to update, maybe that's what you're experiencing.  Nothing I can really do about that since any update pulls from the API and the API only updates once the thermostat has changed.  Ex. if you set the thermostat from 74 to 75, the integration sends the command, but then it polls the API for the current setting and gets the old 74 back.  It may take until another update to get the actual 75.  I've done some mitigations in the code to delay the update, but it doesn't always work.

**Comment by jlabataille** [comment]
Okay. Thanks for looking into it.
